(() => {
const loader=document.querySelector('.loader');
window.addEventListener('load',()=>setTimeout(()=>loader.classList.add('hide'),650));
const dot=document.querySelector('.cursor-dot'), ring=document.querySelector('.cursor-ring');
if(matchMedia('(pointer:fine)').matches){let mx=innerWidth/2,my=innerHeight/2,rx=mx,ry=my;dot.style.display='block';ring.style.display='block';addEventListener('mousemove',e=>{mx=e.clientX;my=e.clientY;dot.style.left=mx+'px';dot.style.top=my+'px'});const loop=()=>{rx+=(mx-rx)*.15;ry+=(my-ry)*.15;ring.style.left=rx+'px';ring.style.top=ry+'px';requestAnimationFrame(loop)};loop();document.querySelectorAll('a,.project,.service').forEach(el=>{el.addEventListener('mouseenter',()=>ring.classList.add('hover'));el.addEventListener('mouseleave',()=>ring.classList.remove('hover'))})}
document.querySelectorAll('.magnetic').forEach(el=>{el.addEventListener('mousemove',e=>{const r=el.getBoundingClientRect();el.style.transform=`translate(${(e.clientX-r.left-r.width/2)*.12}px,${(e.clientY-r.top-r.height/2)*.12}px)`});el.addEventListener('mouseleave',()=>el.style.transform='')});
const stats=document.querySelectorAll('[data-count]');const obs=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){const el=entry.target,target=+el.dataset.count;let start=0;const step=()=>{start=Math.min(target,start+Math.max(1,Math.ceil(target/45)));el.textContent=start+(target===15?'+':'');if(start<target)requestAnimationFrame(step)};step();obs.unobserve(el)}}),{threshold:.6});stats.forEach(s=>obs.observe(s));
const revealObs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in');revealObs.unobserve(e.target)}}),{threshold:.08});document.querySelectorAll('.service,.project,.stats div,.intro-bottom').forEach(e=>{e.style.opacity='0';e.style.transform='translateY(24px)';e.style.transition='opacity .75s ease,transform .75s cubic-bezier(.2,.8,.2,1)';revealObs.observe(e)});const style=document.createElement('style');style.textContent='.in{opacity:1!important;transform:none!important}';document.head.appendChild(style);
document.querySelectorAll('a[href^="#"]').forEach(a=>a.addEventListener('click',e=>{const id=a.getAttribute('href');if(id.length>1){e.preventDefault();document.querySelector(id)?.scrollIntoView({behavior:'smooth'})}}));
})();